### ISSUE TITLE
Header Component Displays "LTR" for site title when viewed on mobile screen size

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/lux-design-system#233]
### Expected behavior
When viewed in smaller screen size I expect to see the title of the application I'm using displayed alongside the Library Logo. 

### Actual behavior
See these screenshots from approvals when taken from a screen size that invokes the mobile breakpoint. You see the letters "LTR" instead of the name of the application (i.e. Travel Requests). 

<img width="456" alt="Screenshot 2024-06-20 at 2 17 18 PM" src="https://github.com/pulibrary/lux-design-system/assets/278825/aab45398-1b23-4ba0-8413-e8dd1eedc94a">
<img width="453" alt="Screenshot 2024-06-20 at 2 07 23 PM" src="https://github.com/pulibrary/lux-design-system/assets/278825/4021ab78-cca6-4700-ba60-a53dc4b6a30d">

### Steps to replicate
Visit any application that uses the LUX Library Header component such as approvals.princeton.edu

### Impact of this bug
Header of website looks wonky on small screen sizes. Appears to happen in all major Mac browsers and on a Samsung Galaxy phone with Chrome.

**Comment by christinach** [comment]
For some reason this was set to be like that in small screens. It is not a bug. It is the html abbr-name="LTR". We can remove it.

**Comment by christinach** [comment]
The reason is that absence and travel requests was initially called https://github.com/pulibrary/lux-design-system/blob/546a5ee5e294ee80086b61e837908160b1b6745c/src/components/LuxLibraryHeader.vue#L192. The name was too long this is why in lux we defined an abbr-name attribute for screens smaller than 900px. 
We [renamed](https://github.com/pulibrary/approvals/pull/1156) the app to be 'Travel Requests'. I believe it fits in small screens and we can now update this abbr-name attribute to have the full name of the application.

**Comment by christinach** [comment]
The comment above is specific for approvals. In the case of Lux we need to add a new media query to better handle  abbr-name in smaller screens.
